### ISSUE TITLE
Provide valid mmt.jar releases without shebangs

### ISSUE THREAD

**Issue by ComFreek** [UniFormal/MMT#288]
For example, `mmt.jar` from the [9th Git release](https://github.com/UniFormal/MMT/releases/tag/20-Dec-2017) contains:
```
#!/bin/bash
exec /usr/bin/java -Xmx2048m -jar "$0" "$@"
PK...
```

As JAR files are built on ZIP files and ZIP files do not specify shebang compatibility, it is not guaranteed that these JARs will work across systems. Indeed, it **breaks** one of my projects, where I reference the JAR in my SBT build file: Even though the JAR is on the classpath, its classes are not found because of the two lines at the top of the file. Removing them solved the issue.

**Comment by tkw1536** [comment]
I will have a look at this, in principal it should be as easy as removing lines https://github.com/UniFormal/MMT/blob/master/src/build.sbt#L136-L137. 

@florian-rabe I do not see the need to include the shebang line at all, since we provide https://github.com/UniFormal/MMT/blob/master/deploy/mmt for users that want to use MMT as a shell script. Was there any particular technical reason for including this in the first place?

**Comment by florian-rabe** [comment]
I don't know any user who uses the shebang line.

So we can just remove those lines from the sbt file.

**Comment by tkw1536** [comment]
This has been fixed in devel and should go into master with Release 10 (January 30th).
