### ISSUE TITLE
Query server interface: "http://cds.omdoc.org/" prepended to request

### ISSUE THREAD

**Issue by freifrauvonbleifrei** [UniFormal/MMT#301]
Hi,

I am using the query interface to get the current omdoc content of theories. So far, this had worked through some code that I basically stole from MMTPy's implementation that just posts something of the form 
`<function name="presentDecl" param="xml"><literal><uri path=" $TheoryPath$ "/></literal></function>`.

This seems to not be working any more, as "http://cds.omdoc.org/" seems to precede the submitted URI. See the screenshot for details.
![screenshot from 2018-02-07 13-44-35](https://user-images.githubusercontent.com/9729409/35917218-97c38f6c-0c0d-11e8-92a3-c2dc9f5fd0bb.png)

Am I doing something wrong here?

**Comment by tkw1536** [comment]
@freifrauvonbleifrei POST Bodies and XML attributes should not be urlescaped. This is not an issue with MMT, but one with your implementation.

**Comment by freifrauvonbleifrei** [comment]
jup, that's right. we might consider a more helpful error message though :)

**Comment by tkw1536** [comment]
IMO in general, I think we should avoid sending stack traces to the enduser -- It's just confusing and likely not helpful for people other than Florian, Dennis or (sometimes) me. 

In this instance however it's hard to detect that the user sent an urlescaped url -- would introduce a lot of overhead.

**Comment by freifrauvonbleifrei** [comment]
No, and that was not my suggestion. It might be better to say that the string is invalid than to prepend something and to say it is invalid - because it obviously is. But of course that is up to you as a developer.

**Comment by tkw1536** [comment]
Maybe some more detailed explanation of the problem here:

The default behaviour of MMT is to interpret all URIs as relative to a certain base (the "prefix" that got added) -- unless they start with a protocol (like http://). 

The very first thing MMT does during parsing of the XML is to resolve potentially relative urls into absolute ones. During this step MMT does not know what the URI is going to be used for - hence it can not check validity. The error only arises in a much later step -- the execution of the query. 

Thus the URI you say is "wrong" could actually be fully valid -- if someone write the query with a relative one.
