### ISSUE TITLE
classify and clean up old branches

### ISSUE THREAD

**Issue by kohlhase** [UniFormal/MMT#338]
Almost all old branches seem stale, we should see what they (try to) contributed and clean them up.

**Comment by florian-rabe** [comment]
Well, that's what happens when you use git :)

But seriously, any branch that doesn't have a 'sponsor' can be deleted without inspection.

I'm sponsoring master and devel.

**Comment by tkw1536** [comment]
I have deleted two branches I created some time ago and no longer need. 
We currently have the following branches (in order of relevance):
* release, master, devel: Obvious
* [`imps`](https://github.com/UniFormal/MMT/tree/imps): @jbetzend is doing work on this branch
* [`no-unmanaged-jars`](https://github.com/UniFormal/MMT/tree/no-unmanaged-jars): I am using this to test a version of MMT that uses sbt / maven instead of unmanaged jars for dependencies and mentioned something along those lines in the last MMT meeting
* [`graphoptimization`](https://github.com/UniFormal/MMT/tree/graphoptimization): has 28 commits on it; we should look at what this is
* [`guidedtours`](https://github.com/UniFormal/MMT/tree/guidedtours): has a single commit on it that seems to mostly change whitespace and commenting out code; can this go?

**Comment by kohlhase** [comment]
thanks for your effort. 

> graphoptimization: has 28 commits on it; we should look at what this is

I think this is the work by Michael Banken, he works on reducing spurious improrts in graphs. I think this is valuable functionality to have. If I remember correctly, the code should be (almost?) finished. The Problem is that we have not seen Michael in a while. 

> guidedtours: has a single commit on it that seems to mostly change whitespace and commenting out code; can this go?

this seems a candidate for deletion.

**Comment by kohlhase** [comment]
I have deleted the `guidedtours` branch, all other branches seem active
