### ISSUE TITLE
Creating views inside an Isabelle theory

### ISSUE THREAD

**Issue by makarius** [UniFormal/MMT#397]
This is MMT/babd7ce0b2a0 and Isabelle/b9aca3b9619f.

I am presently importing locale dependencies (inclusions) like this:

        for (dep <- segment.locale_dependencies if dep.is_inclusion) {
            decl_error(dep.entity) {
              val item = thy_draft.declare_item(dep.entity)
              val content = thy_draft.content

              val from = OMS(content.get_locale(dep.source).global_name)
              val to = OMS(content.get_locale(dep.target).global_name)

              // FIXME !?
              val view = DeclaredView(thy_doc_path, item.local_name, from, to, false)
              controller.add(view)
            }
          }

The view should appear in the enclosing Isabelle theory, but this does not quite work. Which DPath, MPath wiring is required here?

**Comment by florian-rabe** [comment]
I've committed a fix, which also changes the name of the theory built from the locale.

Rules:
* the views are treated in the same way as the theories obtained from the locales; both are wrapped in NestedModule
* to build a theory/view with local name L in a theory with parent P and local name T:
  * construct a theory/view with parent P and local name T/L
  * wrap it in a NestedModule with home T and name L

(The whole thing is unnecessarily complicated because I retrofitted nested modules years after making the fundamental design choices. A simplification is planned as part of a bigger overhaul.)

**Comment by makarius** [comment]
Problem still open: views don't show up in the theory document (e.g. see c5e3cdf2c8a555d646cb446c10f2230d3403e21c).

**Comment by florian-rabe** [comment]
Can you name a simple example of a theory with nested theories and views and commit it to mathhub?

**Comment by makarius** [comment]
See now https://gl.mathhub.info/Isabelle/Distribution e.g. theory FOL-ex.Locale_Test1 should have the following inclusions:

      Locale_Test1.semi -> Locale_Test1.lgrp
      Locale_Test1.semi -> Locale_Test1.perturbation
      Locale_Test1.logic -> Locale_Test1.use_decl
      Locale_Test1.logic_def -> Locale_Test1.logic_def2
      Locale_Test1.semi -> Locale_Test1.semi_hom_loc
      Locale_Test1.semi -> Locale_Test1.rgrp
      Locale_Test1.rgrp -> Locale_Test1.lgrp
      Locale_Test1.lgrp -> Locale_Test1.rgrp
      Locale_Test1.order' -> Locale_Test1.order_with_def
      Locale_Test1.logic2 -> Locale_Test1.logic
      Locale_Test1.logic -> Locale_Test1.logic_a
      Locale_Test1.logic -> Locale_Test1.logic_b
      Locale_Test1.logic_b -> Locale_Test1.logic_a
      Locale_Test1.reflexive -> Locale_Test1.mixin
      Locale_Test1.mixin -> Locale_Test1.mixin2
      Locale_Test1.reflexive -> Locale_Test1.mixin3
      Locale_Test1.reflexive -> Locale_Test1.mixin4_base
      Locale_Test1.mixin4_base -> Locale_Test1.mixin4_mixin
      Locale_Test1.mixin4_base -> Locale_Test1.mixin4_copy
      Locale_Test1.reflexive -> Locale_Test1.mixin5_base
      Locale_Test1.mixin5_base -> Locale_Test1.mixin5_inherited
      Locale_Test1.reflexive -> Locale_Test1.mixin6_base
      Locale_Test1.mixin5_base -> Locale_Test1.mixin6_inherited
      Locale_Test1.reflexive -> Locale_Test1.mixin7_base
      Locale_Test1.reflexive -> Locale_Test1.mixin7_inherited
      Locale_Test1.mixin7_base -> Locale_Test1.mixin7_inherited
      Locale_Test1.reflexive -> Locale_Test1.mixin_thy_merge
      Locale_Test1.semi -> Locale_Test1.dgrp
      Locale_Test1.dgrp -> Locale_Test1.lgrp
      Locale_Test1.roundup -> Locale_Test1.roundup

**Comment by florian-rabe** [comment]
I've made a fix in the Isabelle Importer regarding the domain/codomain of views.

Details: They must be given as MPath (i.e., namespace?theory/locale), not GlobalName (i.e., namespace?theory?locale). The toMPath method does that conversion.

The previously generated views were ill-formed (even though serialization went through) and were discarded while reading the XML files later on. That's why you didn't see them at all.
It should work better now, but I'm not sure if all bugs are fixed.

**Comment by makarius** [comment]
OK, I see view items in the HTML output and the underlying OMDoc. It is future work to do something useful with them: presently they merely document direct inclusions of theories.
