### ISSUE TITLE
Unicode weirdness with mmt make pdflatex

### ISSUE THREAD

**Issue by jbetzend** [UniFormal/MMT#481]
Currently, there is some weirdness with _some_ German unicode in stex. For example, if one builds a file that has (or includes) a `ß`¹ with `mmt build pdflatex`, it shows up as `SS` in the resulting PDF. If you run just `pdflatex` over the same file, it works as intended.

This is not acceptable and should be fixed.

----
[1]: Such as `.../MiKoCourses/IWGS/source/SS19/exam.tex`

**Comment by kohlhase** [comment]
I think the problem is that `mmt build pdflatex` uses xeTeX under the hood and not pdflatex. xeTeX is unicode-aware, and has a better understandig of unicode. I am not sure that we can fix this (apart from fixing the unicode errors in the source code which were created by copy/paste from Libreoffice.
